
db_auth_address:
  database_name: todo
  hostname: 127.0.0.1
  username: root
  password: 123456
  port: 3306
  options: charset=utf8mb4&parseTime=True&loc=UTC&interpolateParams=true
  ssl_client_key:
  ssl_client_cert:
  ssl_ca:
  max_open_conns: 100
  max_idle_conns: 10
  max_life_time: 1000